
package calculadora;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JTextField;

/**
 *
 * @author heatscar
 */
public class frameCalculadora extends javax.swing.JFrame implements KeyListener{
    String numero1;
    String operacion;
    String numero2;
    /**
     * Creates new form frameCalculadora
     */
    public frameCalculadora() {
        initComponents();
        addKeyListener(this);
        setFocusable(true);
    }

    public void keyTyped(KeyEvent e){
        System.out.println(e.getKeyChar());
        switch(e.getKeyChar()){
            case '1': boton1.doClick();
                     break;
            case '2': boton2.doClick();
                     break;
            case '3': boton3.doClick();
                    break;
            case '4': boton4.doClick();
                    break;
            case '5': boton5.doClick();
                     break;
            case '6': boton6.doClick();
                     break;
            case '7': boton7.doClick();
                     break;
            case '8': boton8.doClick();
                     break;
            case '9': boton9.doClick();
                     break;
            case '-': botonResta.doClick();
                     break;
            case '/': botonDivision.doClick();
                     break;
            case '*': botonMultiplicacion.doClick();
                     break;
            case'+':botonSuma.doClick();
                     break;
            case'=':botonIgual.doClick();
                    break;
        }
    }
    
    @Override
    public void keyPressed(KeyEvent e) {
        
    }
    @Override
    public void keyReleased(KeyEvent e) {
        
    }
    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumeros = new javax.swing.JTextField();
        boton0 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonCambiarSigno = new javax.swing.JButton();
        botonPorciento = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        backspace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().setLayout(null);

        textNumeros.setBackground(java.awt.Color.lightGray);
        textNumeros.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        textNumeros.setForeground(java.awt.Color.black);
        textNumeros.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textNumeros.setBorder(null);
        textNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumerosActionPerformed(evt);
            }
        });
        textNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumerosKeyTyped(evt);
            }
        });
        getContentPane().add(textNumeros);
        textNumeros.setBounds(20, 20, 280, 50);

        boton0.setBackground(new java.awt.Color(255, 255, 255));
        boton0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton0.setText("0");
        boton0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        getContentPane().add(boton0);
        boton0.setBounds(20, 320, 140, 50);

        boton1.setBackground(new java.awt.Color(255, 255, 255));
        boton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton1.setText("1");
        boton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1);
        boton1.setBounds(20, 270, 70, 50);

        boton2.setBackground(new java.awt.Color(255, 255, 255));
        boton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton2.setText("2");
        boton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2);
        boton2.setBounds(90, 270, 70, 50);

        boton3.setBackground(new java.awt.Color(255, 255, 255));
        boton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton3.setText("3");
        boton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3);
        boton3.setBounds(160, 270, 70, 50);

        boton4.setBackground(new java.awt.Color(255, 255, 255));
        boton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton4.setText("4");
        boton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton4);
        boton4.setBounds(20, 220, 70, 50);

        boton5.setBackground(new java.awt.Color(255, 255, 255));
        boton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton5.setText("5");
        boton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton5);
        boton5.setBounds(90, 220, 70, 50);

        boton6.setBackground(new java.awt.Color(255, 255, 255));
        boton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton6.setText("6");
        boton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton6);
        boton6.setBounds(160, 220, 70, 50);

        boton7.setBackground(new java.awt.Color(255, 255, 255));
        boton7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton7.setText("7");
        boton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton7);
        boton7.setBounds(20, 170, 70, 50);

        boton8.setBackground(new java.awt.Color(255, 255, 255));
        boton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton8.setText("8");
        boton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton8);
        boton8.setBounds(90, 170, 70, 50);

        boton9.setBackground(new java.awt.Color(255, 255, 255));
        boton9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton9.setText("9");
        boton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton9);
        boton9.setBounds(160, 170, 70, 50);

        botonBorrar.setBackground(new java.awt.Color(255, 51, 0));
        botonBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonBorrar.setText("C");
        botonBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrar);
        botonBorrar.setBounds(20, 120, 70, 50);

        botonCambiarSigno.setBackground(new java.awt.Color(204, 204, 204));
        botonCambiarSigno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonCambiarSigno.setText("+/-");
        botonCambiarSigno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonCambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarSignoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCambiarSigno);
        botonCambiarSigno.setBounds(90, 120, 70, 50);

        botonPorciento.setBackground(new java.awt.Color(204, 204, 204));
        botonPorciento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonPorciento.setText("%");
        botonPorciento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPorciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorcientoActionPerformed(evt);
            }
        });
        getContentPane().add(botonPorciento);
        botonPorciento.setBounds(160, 120, 70, 50);

        botonPunto.setBackground(new java.awt.Color(204, 204, 204));
        botonPunto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonPunto.setText(".");
        botonPunto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(botonPunto);
        botonPunto.setBounds(160, 320, 70, 50);

        botonIgual.setBackground(new java.awt.Color(204, 204, 204));
        botonIgual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonIgual.setText("=");
        botonIgual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(botonIgual);
        botonIgual.setBounds(230, 320, 70, 50);

        botonSuma.setBackground(new java.awt.Color(204, 204, 204));
        botonSuma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonSuma.setText("+");
        botonSuma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        botonSuma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonSumaKeyTyped(evt);
            }
        });
        getContentPane().add(botonSuma);
        botonSuma.setBounds(230, 270, 70, 50);

        botonResta.setBackground(new java.awt.Color(204, 204, 204));
        botonResta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonResta.setText("-");
        botonResta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(botonResta);
        botonResta.setBounds(230, 220, 70, 50);

        botonMultiplicacion.setBackground(new java.awt.Color(204, 204, 204));
        botonMultiplicacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonMultiplicacion.setText("x");
        botonMultiplicacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonMultiplicacion);
        botonMultiplicacion.setBounds(230, 170, 70, 50);

        botonDivision.setBackground(new java.awt.Color(204, 204, 204));
        botonDivision.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonDivision.setText("/");
        botonDivision.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(botonDivision);
        botonDivision.setBounds(230, 120, 70, 50);

        backspace.setBackground(new java.awt.Color(0, 204, 204));
        backspace.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backspace.setText("<-");
        backspace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });
        getContentPane().add(backspace);
        backspace.setBounds(20, 80, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        // TODO add your handling code here:
        if(!textNumeros.getText().equals("")){
            numero1 = textNumeros.getText();
            operacion = "/";
            textNumeros.setText("");
        }
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "1");
        this.requestFocus();
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "2");
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "3");
        
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "4");
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "5");
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "6");
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "7");
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "8");
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "9");
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
        textNumeros.setText(textNumeros.getText() + "0");    
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        // TODO add your handling code here:
        String textoPantalla;
        textoPantalla = textNumeros.getText();
        
        if(textoPantalla.length() <= 0){
            textNumeros.setText("0.");
        }
        else{
            if(!existePunto(textNumeros.getText())){
                textNumeros.setText(textNumeros.getText() + ".");
            }
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        textNumeros.setText("");
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonCambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarSignoActionPerformed
        // TODO add your handling code here:
        Integer numero;
        String textoPantalla;
        textoPantalla = textNumeros.getText();
        
        if(textoPantalla.length() > 0){
            numero = (-1)*Integer.parseInt(textoPantalla);
            textNumeros.setText(numero.toString());
        }
    }//GEN-LAST:event_botonCambiarSignoActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        if(!textNumeros.getText().equals("")){
            numero1 = textNumeros.getText();
            operacion = "-";
            textNumeros.setText("");
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        // TODO add your handling code here:
        if(!textNumeros.getText().equals("")){
            numero1 = textNumeros.getText();
            operacion = "*";
            textNumeros.setText("");
        }
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        String resultado;
        numero2 = textNumeros.getText();

        if(!numero2.equals("")){
            resultado = calculadora(numero1, numero2, operacion);
            textNumeros.setText(resultado);
        }
    }//GEN-LAST:event_botonIgualActionPerformed

    private void textNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumerosActionPerformed
        // TODO add your handling code here:
        textNumeros.setHorizontalAlignment(JTextField.RIGHT);
    }//GEN-LAST:event_textNumerosActionPerformed

    private void botonPorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorcientoActionPerformed
        // TODO add your handling code here:
        if(!textNumeros.getText().equals("")){
            numero1 = textNumeros.getText();
            operacion = "%";
            textNumeros.setText("");
        }
    }//GEN-LAST:event_botonPorcientoActionPerformed

    private void textNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumerosKeyTyped
        // TODO add your handling code here:
        if (!(evt.getKeyChar()>= '0' && evt.getKeyChar() <='9') &&
                evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && 
                evt.getKeyChar() != '-' ){
            evt.consume();
        }
    }//GEN-LAST:event_textNumerosKeyTyped

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        // Evento para el boton de borrar nuúmeros uno por uno
        String cadena;
        cadena = textNumeros.getText();
        if(cadena.length()>0){
        cadena = cadena.substring(0, cadena.length()-1);
        textNumeros.setText(cadena);
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void botonSumaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonSumaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonSumaKeyTyped

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
        if(!textNumeros.getText().equals("")){
            numero1 = textNumeros.getText();
            operacion = "+";
            textNumeros.setText("");
        }
    }//GEN-LAST:event_botonSumaActionPerformed

    public static boolean existePunto(String textoPantalla){
        boolean existePunto;
        existePunto = false;
        for(int i = 0; i < textoPantalla.length(); i++){
            if(textoPantalla.substring(i, i + 1).equals(".")){
                existePunto = true;
            }
        }
        
        return existePunto;
    }    
    
    public static String calculadora(String numero1, String numero2, String operacion){
        Double resultado = 0.0;
        String respuesta;
        
        if(operacion.equals("+")){
            resultado = (Double.parseDouble(numero1) + Double.parseDouble(numero2));
        }
        
        if(operacion.equals("-")){
            resultado = Double.parseDouble(numero1) - Double.parseDouble(numero2);
        }
        
        if(operacion.equals("*")){
            resultado = Double.parseDouble(numero1) * Double.parseDouble(numero2);
        }
        
        if(operacion.equals("/")){
            resultado = Double.parseDouble(numero1) / Double.parseDouble(numero2);
        }
        
        if(operacion.equals("%")){
            resultado = Double.parseDouble(numero1) * (Double.parseDouble(numero2) / 100);
        }
        
        respuesta = resultado.toString();
        return respuesta;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCalculadora().setVisible(true);
                 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspace;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCambiarSigno;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonPorciento;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JTextField textNumeros;
    // End of variables declaration//GEN-END:variables
}
